logging:
  level:
    org.springframework.web: WARN
    com.ote.test: INFO

server:
  port: ${PORT:8080}

spring:
  application.name: Server
  main.banner-mode: LOG
  datasource:
    url: jdbc:h2:./server/database/users
    username: sa
    password: admin
    driver-class-name: org.h2.Driver
    initialize: true
    continue-on-error: true
    platform: h2
  jpa:
    show-sql: false
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate-naming:
      physical-strategy: org.hibernate.boot.mapper.naming.PhysicalNamingStrategyStandardImpl
    ddl-auto: create-drop